export const ADD_ITEM_TO_CART = 'ADD_TO_CART';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAILED = 'ADD_TO_CART_FAILED';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ITEM_FROM_CART_SUCCESS = 'REMOVE_ITEM_FROM_CART_SUCCESS';
export const REMOVE_ITEM_FROM_CART_FAILED = 'REMOVE_ITEM_FROM_CART_FAILED';
